### ISSUE TITLE
Please Add support for ArrayType

### ISSUE THREAD

**Issue by kant111** [amplab/succinct#35]
scala> spark.read.json(rdd)
res59: org.apache.spark.sql.DataFrame = [ProgressionRegex: string, Progressions: array<string> ... 27 more fields]

scala> val flattenedDf = spark.read.json(rdd)
flattenedDf: org.apache.spark.sql.DataFrame = [ProgressionRegex: string, Progressions: array<string> ... 27 more fields]

scala> val flattenedSuccinctDf = flattenedDf.toSuccinctDF
java.lang.IllegalArgumentException: Unexpected type. ArrayType(StringType,true)
  at edu.berkeley.cs.succinct.sql.SuccinctTableRDD$$anonfun$7.apply(SuccinctTableRDD.scala:224)
  at edu.berkeley.cs.succinct.sql.SuccinctTableRDD$$anonfun$7.apply(SuccinctTableRDD.scala:214)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
  at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
  at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
  at edu.berkeley.cs.succinct.sql.SuccinctTableRDD$.min(SuccinctTableRDD.scala:214)
  at edu.berkeley.cs.succinct.sql.SuccinctTableRDD$.apply(SuccinctTableRDD.scala:158)
  at edu.berkeley.cs.succinct.sql.SuccinctTableRDD$.apply(SuccinctTableRDD.scala:176)
  at edu.berkeley.cs.succinct.sql.SuccinctInMemoryRelation.<init>(SuccinctInMemoryRelation.scala:11)
  at edu.berkeley.cs.succinct.sql.package$SuccinctDataFrame.toSuccinctDF(package.scala:33)
  ... 58 elided

**Comment by kant111** [comment]
@anuragkh

**Comment by muditsin** [comment]
+1 on this request. Is the project still active?

**Comment by anuragkh** [comment]
Unfortunately, I don't have sufficient time to add support for this. I am happy to review and merge PRs that address this issue.
