### ISSUE TITLE
IllegalArgumentException when writing SuccinctTable

### ISSUE THREAD

**Issue by luohao** [amplab/succinct#39]
Hi,
I was trying to convert a parquet table to succinct table. But was not able to write it using `saveAsTable()`. 

My code to produce succinct table is fairly straightforward.

```
spark.sql("select * from my_table")
      .write
      .format("edu.berkeley.cs.succinct.sql")
      .option("path", succinctDir)
      .saveAsTable("my_table_succinct")
```

The error messages show the below stacktrace:

```
java.lang.IllegalArgumentException: Negative initial size: -1683087478
	at java.io.ByteArrayOutputStream.<init>(ByteArrayOutputStream.java:74)
	at edu.berkeley.cs.succinct.sql.SuccinctTableRDD$.createSuccinctTablePartition(SuccinctTableRDD.scala:202)
	at edu.berkeley.cs.succinct.sql.SuccinctTableRDD$$anonfun$6.apply(SuccinctTableRDD.scala:163)
	at edu.berkeley.cs.succinct.sql.SuccinctTableRDD$$anonfun$6.apply(SuccinctTableRDD.scala:163)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:797)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:797)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD$$anonfun$8.apply(RDD.scala:336)
	at org.apache.spark.rdd.RDD$$anonfun$8.apply(RDD.scala:334)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1038)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1029)
	at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:969)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1029)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:760)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:334)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:285)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:338)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I guess it exceeds the 2G limit of shuffle partitions and increases `spark.sql.shuffle.partitions` to a large number. However, still get the same error. Is this a misconfiguration in spark or a bug in succinct library?

Thanks.
Hao Luo

**Comment by anuragkh** [comment]
Succinct does not support RDD/DataFrame partitions with sizes > 2GB. This is mainly because the maximum size of an array in java is [~2GB](https://www.quora.com/What-is-the-maximum-size-of-the-array-in-Java), and Succinct internally uses arrays of partition size for its compression algorithms.

You can try increasing the number of partitions in your input and see if the problem still persists.

**Comment by luohao** [comment]
I still couldn't get it to work with our data (2T parquet dataset). I did repartition the dataset but still hit the following error.

```
java.lang.IllegalStateException: unread block data
        at java.io.ObjectInputStream$BlockDataInputStream.setBlockDataMode(ObjectInputStream.java:2781)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1603)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2285)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2209)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2067)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1571)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
        at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:75)
        at org.apache.spark.serializer.DeserializationStream$$anon$1.getNext(Serializer.scala:168)
        at org.apache.spark.util.NextIterator.hasNext(NextIterator.scala:73)
        at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
        at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
        at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1336)
        at scala.collection.TraversableOnce$class.aggregate(TraversableOnce.scala:214)
        at scala.collection.AbstractIterator.aggregate(Iterator.scala:1336)
        at org.apache.spark.rdd.RDD$$anonfun$aggregate$1$$anonfun$22.apply(RDD.scala:1113)
        at org.apache.spark.rdd.RDD$$anonfun$aggregate$1$$anonfun$22.apply(RDD.scala:1113)
        at org.apache.spark.SparkContext$$anonfun$33.apply(SparkContext.scala:2125)
        at org.apache.spark.SparkContext$$anonfun$33.apply(SparkContext.scala:2125)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:108)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:338)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

Any suggestions on how to convert large dataset into succinct format?

**Comment by anuragkh** [comment]
This error doesn't seem to stem from Succinct. Are you sure you're able to read the dataset as is? Do you have a rough idea of how big each partition is?

**Comment by luohao** [comment]
My dataset is about 1.5TB (3000 parquet files, each of which is around 500MB). I can query the whole dataset using Spark. It fails when trying to write it to the persistent table.

Another question is, is there a columnar format built around succinct? The way succinct Dataframe store the columns seem not suitable for OLAP use case.

**Comment by anuragkh** [comment]
Unfortunately, we haven't implemented a columnar format around Succinct. I'm a little tied up, but I'd welcome contributions for a columnar format using Succinct, with [SuccinctTableRDD](https://github.com/amplab/succinct/blob/master/spark/src/main/scala/edu/berkeley/cs/succinct/sql/SuccinctTableRDD.scala) as a starting point.
